# Generated by Django 5.0.1 on 2024-01-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
    ]
